name: build

on: [push, pull_request]

jobs:
  build-matrix:

    strategy:
      matrix:
        arduino-platform: ["arduino:avr"]
        include:
          - arduino-platform: "arduino:avr"
            fqbn: "arduino:avr:unowifi"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install platform
        run: |
          arduino-cli core update-index
          arduino-cli core install ${{ matrix.arduino-platform }}
      - name: Compile Sketch
        run: arduino-cli compile --fqbn ${{ matrix.fqbn }} ./bbn_m5tough_active_boat
