# see: https://github.com/marketplace/actions/test-compile-for-arduino

name: build
on: [push, pull_request]
jobs:
  build:
    name: build for MCU
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Checkout M5Tough library
      uses: actions/checkout@v3
      with:
          repository: m5stack/M5Tough
          ref: master
          path: CustomLibrary_M5Tough # must contain string "Custom"

    - name: Checkout ReactESP library
      uses: actions/checkout@v3
      with:
          repository: mairas/ReactESP
          ref: v2.1.0
          path: CustomLibrary_ReactESP # must also contain string "Custom"

    - name: copy lv_conf.h
      run: |
        mkdir -p /home/runner/Arduino/libraries
        cp /home/runner/work/bbn-m5stack-tough/bbn-m5stack-tough/lv_conf.h-custom /home/runner/Arduino/libraries/lv_conf.h

    - name: Compile sketch
      uses: ArminJo/arduino-test-compile@v3
      with:
        arduino-board-fqbn: esp32:esp32:m5stack-core2
        platform-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
        required-libraries: MQTT@2.5.1,LVGL@8.3.6,ArduinoJson@6.21.2
        sketch-names: "*.ino"
        sketch-names-find-start: bbn_m5tough_active_boat/*
        extra-arduino-cli-args: "--warnings more"
        set-build-path: true
